module.exports = {
    alps: require('./alps'),
    button: require('./button'),
    choc: require('./choc'),
    chocmini: require('./chocmini'),
    diode: require('./diode'),
    smd_diode: require('./smd_diode'),
    jstph: require('./jstph'),
    jumper: require('./jumper'),
    mx: require('./mx'),
    mx_low: require('./mx_low'),
    gatetron_low: require('./gatetron_low'),
    oled: require('./oled'),
    omron: require('./omron'),
    pad: require('./pad'),
    promicro_pretty: require('./promicro_pretty'),
    promicro: require('./promicro'),
    rgb: require('./rgb'),
    rotary: require('./rotary'),
    scrollwheel: require('./scrollwheel'),
    slider: require('./slider'),
    text: require('./text'),
    trrs: require('./trrs'),
    via: require('./via'),
}
